name: hellow
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  syncfusion_flutter_gauges: ^1.0.0-beta

  cupertino_icons: ^0.1.2
  flutter_timer: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

fonts:
- family: Pacifico
  fonts:
    - asset: fonts/Pacifico-Regular.ttf

- family: Bitter-Bold
  fonts:
    - asset: fonts/Bitter-Bold.ttf

- family: Bitter-Regular
  fonts:
    - asset: fonts/Bitter-Regular.ttf
# see https://flutter.dev/custom-fonts/#from-packages

  